name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini

  client1:
    container_name: client1
    image: client:latest
    entrypoint: ["tail", "-f", "/dev/null"]
    environment:
      - CLI_ID=1
      - CLI_BET_NUMBER=67890
      - CLI_DOCUMENT=11223344
      - CLI_FIRST_NAME=John
      - CLI_LAST_NAME=Doe
      - CLI_BIRTHDATE=1990-01-01
    networks:
      - testing_net
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data:/data
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
